version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

  pre_build:
    commands:
      - echo "=== PRE_BUILD ==="
      - echo "Region: $AWS_DEFAULT_REGION"
      - echo "Account: $AWS_ACCOUNT_ID"
      - echo "Repo: $IMAGE_REPO_NAME"
      - echo "Container: $CONTAINER_NAME"
      - docker --version
      - aws --version
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:-latest}
      - echo "REPOSITORY_URI=$REPOSITORY_URI"
      - echo "IMAGE_TAG=$IMAGE_TAG"
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

  build:
    commands:
      - echo "=== BUILD MAVEN ==="
      - mvn clean package -DskipTests
      - echo "=== VALIDANDO JAR ==="
      - ls -lh presentacion/target/
      - echo "=== BUILD DOCKER ==="
      - docker build --no-cache -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo "=== PUSH ECR ==="
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - printf '[{"name":"%s","imageUri":"%s"}]' "$CONTAINER_NAME" "$REPOSITORY_URI:$IMAGE_TAG" > imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json