spring.application.name=api-calendario
server.port=8081

#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.url=jdbc:postgresql://localhost:5432/calendariolaboral
spring.datasource.url=jdbc:postgresql://db-calendario-laboral.cmhowq6mi904.us-east-1.rds.amazonaws.com:5432/calendariolaboral
spring.datasource.username=postgres
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

integracion.festivos.base-url=http://localhost:8080/api/festivos
